// Document-related action types
export const SET_CURRENT_DOCUMENT = "SET_CURRENT_DOCUMENT";
export const UPLOAD_DOCUMENT_REQUEST = "UPLOAD_DOCUMENT_REQUEST";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAILURE = "UPLOAD_DOCUMENT_FAILURE";
export const DOWNLOAD_DOCUMENT_REQUEST = "DOWNLOAD_DOCUMENT_REQUEST";
export const DOWNLOAD_DOCUMENT_SUCCESS = "DOWNLOAD_DOCUMENT_SUCCESS";
export const DOWNLOAD_DOCUMENT_FAILURE = "DOWNLOAD_DOCUMENT_FAILURE";

export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const FETCH_DOCUMENTS_REQUEST = "FETCH_DOCUMENTS_REQUEST";
export const FETCH_DOCUMENTS_SUCCESS = "FETCH_DOCUMENTS_SUCCESS";
export const FETCH_DOCUMENTS_FAILURE = "FETCH_DOCUMENTS_FAILURE";

// Mindmap-related action types
// export const FETCH_MINDMAP_REQUEST = "FETCH_MINDMAP_REQUEST";
// export const FETCH_MINDMAP_SUCCESS = "FETCH_MINDMAP_SUCCESS";
// export const FETCH_MINDMAP_FAILURE = "FETCH_MINDMAP_FAILURE";

// // Chatbot-related action types
// export const FETCH_CHAT_RESPONSE_REQUEST = "FETCH_CHAT_RESPONSE_REQUEST";
// export const FETCH_CHAT_RESPONSE_SUCCESS = "FETCH_CHAT_RESPONSE_SUCCESS";
// export const FETCH_CHAT_RESPONSE_FAILURE = "FETCH_CHAT_RESPONSE_FAILURE";

// // PDF-related action types
// export const DOWNLOAD_PDF_REQUEST = "DOWNLOAD_PDF_REQUEST";
// export const DOWNLOAD_PDF_SUCCESS = "DOWNLOAD_PDF_SUCCESS";
// export const DOWNLOAD_PDF_FAILURE = "DOWNLOAD_PDF_FAILURE";

// // Node summary action types
// export const FETCH_NODE_SUMMARY_REQUEST = "FETCH_NODE_SUMMARY_REQUEST";
// export const FETCH_NODE_SUMMARY_SUCCESS = "FETCH_NODE_SUMMARY_SUCCESS";
// export const FETCH_NODE_SUMMARY_FAILURE = "FETCH_NODE_SUMMARY_FAILURE";

// // Node questions action types
// export const FETCH_NODE_QUESTIONS_REQUEST = "FETCH_NODE_QUESTIONS_REQUEST";
// export const FETCH_NODE_QUESTIONS_SUCCESS = "FETCH_NODE_QUESTIONS_SUCCESS";
// export const FETCH_NODE_QUESTIONS_FAILURE = "FETCH_NODE_QUESTIONS_FAILURE";
