// Document-related action types
export const SET_CURRENT_DOCUMENT = "SET_CURRENT_DOCUMENT";
export const UPLOAD_DOCUMENT_REQUEST = "UPLOAD_DOCUMENT_REQUEST";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAILURE = "UPLOAD_DOCUMENT_FAILURE";
export const DOWNLOAD_DOCUMENT_REQUEST = "DOWNLOAD_DOCUMENT_REQUEST";
export const DOWNLOAD_DOCUMENT_SUCCESS = "DOWNLOAD_DOCUMENT_SUCCESS";
export const DOWNLOAD_DOCUMENT_FAILURE = "DOWNLOAD_DOCUMENT_FAILURE";
export const TOGGLE_IS_DOCUMENT_VISIBLE = "TOGGLE_IS_DOCUMENT_VISIBLE";

export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const FETCH_DOCUMENTS_REQUEST = "FETCH_DOCUMENTS_REQUEST";
export const FETCH_DOCUMENTS_SUCCESS = "FETCH_DOCUMENTS_SUCCESS";
export const FETCH_DOCUMENTS_FAILURE = "FETCH_DOCUMENTS_FAILURE";

// Mindmap-related action types
export const FETCH_MINDMAP_REQUEST = "FETCH_MINDMAP_REQUEST";
export const FETCH_MINDMAP_SUCCESS = "FETCH_MINDMAP_SUCCESS";
export const FETCH_MINDMAP_FAILURE = "FETCH_MINDMAP_FAILURE";
export const SET_ROOT_NODE_ID = "SET_ROOT_NODE_ID";
export const SET_SELECTED_NODE_ID = "SET_SELECTED_NODE_ID";
export const TOGGLE_IS_MINDMAP_VISIBLE = "TOGGLE_IS_MINDMAP_VISIBLE";

// Chatbot-related action types
export const FETCH_CHAT_RESPONSE_REQUEST = "FETCH_CHAT_RESPONSE_REQUEST";
export const FETCH_CHAT_RESPONSE_SUCCESS = "FETCH_CHAT_RESPONSE_SUCCESS";
export const FETCH_CHAT_RESPONSE_FAILURE = "FETCH_CHAT_RESPONSE_FAILURE";
export const TOGGLE_IS_CHATBAR_VISIBLE = "TOGGLE_IS_CHATBAR_VISIBLE";
export const RESET_CHATS = "RESET_CHATS";

// node details-related action types
export const TOGGLE_IS_NODE_DETAILS_VISIBLE = "TOGGLE_IS_NODE_DETAILS_VISIBLE";

// Node content-related action types
export const FETCH_NODE_CONTENT_REQUEST = "FETCH_NODE_CONTENT_REQUEST";
export const FETCH_NODE_CONTENT_SUCCESS = "FETCH_NODE_CONTENT_SUCCESS";
export const FETCH_NODE_CONTENT_FAILURE = "FETCH_NODE_CONTENT_FAILURE";

// Node summary action types
export const FETCH_NODE_SUMMARY_REQUEST = "FETCH_NODE_SUMMARY_REQUEST";
export const FETCH_NODE_SUMMARY_SUCCESS = "FETCH_NODE_SUMMARY_SUCCESS";
export const FETCH_NODE_SUMMARY_FAILURE = "FETCH_NODE_SUMMARY_FAILURE";

// Node  word cloud action types
export const FETCH_WORD_CLOUD_REQUEST = "FETCH_WORD_CLOUD_REQUEST";
export const FETCH_WORD_CLOUD_SUCCESS = "FETCH_WORD_CLOUD_SUCCESS";
export const FETCH_WORD_CLOUD_FAILURE = "FETCH_WORD_CLOUD_FAILURE";

// Node questions action types
export const FETCH_NODE_QUESTIONS_REQUEST = "FETCH_NODE_QUESTIONS_REQUEST";
export const FETCH_NODE_QUESTIONS_SUCCESS = "FETCH_NODE_QUESTIONS_SUCCESS";
export const FETCH_NODE_QUESTIONS_FAILURE = "FETCH_NODE_QUESTIONS_FAILURE";
export const RESET_NODE_QUESTIONS = "RESET_NODE_QUESTIONS";
