export default [
  { text: "elysium", value: 18 },
  { text: "mistake", value: 10 },
  { text: "thought", value: 10 },
  { text: "bad", value: 9 },
  { text: "correct", value: 8 },
  { text: "day", value: 5 },
  { text: "magical", value: 12 },
  { text: "journey", value: 14 },
  { text: "prologue", value: 7 },
  { text: "destiny", value: 11 },
  { text: "lyra", value: 8 },
  { text: "characters", value: 5 },
  { text: "creatures", value: 18 },
  { text: "dragons", value: 20 },
  { text: "ancient", value: 4 },
  { text: "prophecy", value: 14 },
  { text: "pages", value: 2 },
  { text: "adventure", value: 23 },
  { text: "heart", value: 12 },
  { text: "spark", value: 9 },
  { text: "introduction", value: 7 },
  { text: "creatures", value: 8 },
  { text: "dragons", value: 6 },
];
